### ISSUE TITLE
Unity fails to properly import or understand the preset materials

### ISSUE THREAD

**Issue by bonkmaykr** [PavelDoGreat/Super-Blur#12]
I litterally have no idea where it went wrong since this isn't my code so can the developer just give me an explanation on what I'm doing because these materials are broken

![this is broken ah](https://lh3.googleusercontent.com/C4d5MFSxVAG9iVjZF1UqSobMCbLeIKwrGfM2ydv2K1Cwmuy1WNtROD8eX9asskYvqZaNtDJ9hXU8ogidTJmv17VYWOueGFzWpudPGI_-anRhSvdRZiR2W3h0Fxby_M-EdmcXs6e_fic4qWgL-JLB1M4_bmQOPMGI1Gz52uVCJlXq_IgxTJBOVQgWVTVKalHxEfFEoBBTH4nua1qKTgks0BlCXfN2w30g2mXpI6mHuvGyHs6fwls-8GEcQL7MR4CcQyqNwb0J9uag8lUSdkSWlTeHD_4BSWqeFow7pm_0KG-iD7YRWjTGZmGmQcVBufwecYi5tiI-YXMnJxIrmzR31FBYSzhWmr9NrQ7Lp8Po9G5xi4FdhibichKI9-94pBQzHtffeCpZvLjwNFeE7z7dGDE4iGw6cVdMBb1t9OJRbHoEJw3BmqGDmupudtSPY42S5vNWfcUiS5w4FyAaGcY-A_GtC0SzD1n8aurYMqCXe1YUmjgHNfzOxRJk3ny3_BRIxjBvvAv4LotW3JNALPGiorYpyjNZHqQVZ5VMuHMM2ePXqkRBWWmFKqEU4E3ts82P=w1920-h920)

**Comment by Cambesa** [comment]
select other shaders, UI/SuperBlur and Custom/SuperBlurPostEffect.

**Comment by bonkmaykr** [comment]
Alright thanks, I will try that. @Cambesa 


EDIT: Although I still haven't figured out how to get it to work entirely (I'm getting there) it did solve the problem, the materials are working. Thanks

**Comment by VoodaGod** [comment]
#17 pull request with updated README
