### ISSUE TITLE
Does Not Work With UI Mask

### ISSUE THREAD

**Issue by ghost** [PavelDoGreat/Super-Blur#9]
Using a UI mask on this causes the effect to disappear or draw incorrectly. Allowing this to work with a UI mask is very important as not everyone has squares for a HUD.

**Comment by andersemil** [comment]
@CARVERD12 did you find a solution to this problem?

**Comment by CARVERD12** [comment]
No.

Sent from my iPhone

On Sep 6, 2018, at 8:07 AM, Anders Emil <notifications@github.com<mailto:notifications@github.com>> wrote:


@CARVERD12<https://github.com/CARVERD12> did you find a solution to this problem?
